# codecov.yml

codecov:
  require_ci_to_pass: yes

fixes:
  - "git/tofu/::"

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 10%
        if_not_found: success

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
